language: cpp

install:
    - git submodule init
    - git submodule update
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -y
    - sudo apt-get install -y gcc-4.8
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50

script:
    - ./configure.py
    - make all
