language: cpp

compiler: gcc 

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get install 

install:
    # g++4.8.1
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8" CC="gcc-4.8"
    - git submodule init
    - git submodule update

script:
    - ./configure.py
    - make all
